# Generated by Django 4.2.6 on 2023-10-26 10:16

import accounts.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_code', models.CharField(max_length=11, validators=[accounts.validators.validate_id_code_length, accounts.validators.validate_integer])),
            ],
        ),
        migrations.CreateModel(
            name='LimitedLiabilityCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('registration_code', models.CharField(max_length=7)),
                ('establishment_date', models.DateField()),
                ('total_capital_size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_code', models.CharField(max_length=11, validators=[accounts.validators.validate_id_code_length, accounts.validators.validate_integer])),
            ],
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_count', models.PositiveIntegerField()),
                ('is_founder', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.limitedliabilitycompany')),
                ('legal_entity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.legalentity')),
                ('natural_person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.naturalperson')),
            ],
        ),
        migrations.AddField(
            model_name='limitedliabilitycompany',
            name='shareholders',
            field=models.ManyToManyField(related_name='shareholders', to='accounts.shareholder'),
        ),
    ]
