# Generated by Django 4.2.6 on 2023-10-26 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limitedliabilitycompany',
            name='shareholders',
        ),
        migrations.RemoveField(
            model_name='shareholder',
            name='company',
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.legalentity'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='natural_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.naturalperson'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='company',
            field=models.ManyToManyField(to='accounts.limitedliabilitycompany'),
        ),
    ]
