# Generated by Django 4.2.6 on 2023-10-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_limitedliabilitycompany_shareholders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='registration_code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='id_code',
            field=models.CharField(max_length=11),
        ),
    ]
