# Generated by Django 4.2.6 on 2023-10-26 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_legalentity_registration_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shareholder',
            name='company',
        ),
        migrations.AddField(
            model_name='shareholder',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.limitedliabilitycompany'),
        ),
    ]
