# Generated by Django 4.2.6 on 2023-10-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_shareholder_company_shareholder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalperson',
            name='id_code',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
