# Generated by Django 4.2.6 on 2023-10-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_shareholder_company_shareholder_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareholder',
            name='is_founder',
            field=models.BooleanField(default=True),
        ),
    ]
