# Generated by Django 4.2.6 on 2023-10-28 11:50

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_shareholder_is_founder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='registration_code',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='limitedliabilitycompany',
            name='establishment_date',
            field=models.DateField(validators=[accounts.validators.establishment_date_validator]),
        ),
        migrations.AlterField(
            model_name='limitedliabilitycompany',
            name='registration_code',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='limitedliabilitycompany',
            name='total_capital_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2500)]),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='id_code',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AddConstraint(
            model_name='shareholder',
            constraint=models.CheckConstraint(check=models.Q(('legal_entity__isnull', False), ('natural_person__isnull', False), _negated=True), name='either_natural_person_or_legal_entity'),
        ),
    ]
