# Generated by Django 4.2.6 on 2023-10-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_naturalperson_id_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='registration_code',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='limitedliabilitycompany',
            name='registration_code',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
