# Generated by Django 4.2.6 on 2023-10-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_legalentity_registration_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='registration_code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='limitedliabilitycompany',
            name='registration_code',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='naturalperson',
            name='id_code',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='is_founder',
            field=models.BooleanField(default=True),
        ),
    ]
